/*
 That script help you cleanup the draft pages and improve speedup of Synchrony diagnostics
 link: https://confluence.atlassian.com/confkb/how-to-manually-remove-stale-drafts-from-confluence-database-951392345.html

*/
SELECT d.CONTENTID, d.TITLE, d.PREVVER, d.LASTMODDATE, c.LASTMODDATE
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE;

-- action
SET SQL_SAFE_UPDATES=0;

DELETE FROM NOTIFICATIONS WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM CONFANCESTORS WHERE ANCESTORID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM CONFANCESTORS WHERE DESCENDENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM BODYCONTENT WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM CONTENTPROPERTIES WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM LINKS WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM CONTENT_LABEL WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM extrnlnks WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM likes WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

DELETE FROM CONTENT WHERE CONTENTID IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);

/* Changed on the the Confluence 7.4.x */
DELETE FROM usercontent_relation WHERE targetcontentid IN (SELECT d.CONTENTID
FROM CONTENT d
JOIN CONTENT c
  ON d.PREVVER = c.CONTENTID
WHERE d.CONTENT_STATUS = 'draft'
  AND d.PREVVER IS NOT NULL
  AND c.LASTMODDATE > d.LASTMODDATE);