-- it helps to to understand the problem with ancestors
-- https://jira.atlassian.com/browse/CONFSERVER-54945
-- https://jira.atlassian.com/browse/CONFSERVER-25188

SELECT A.ANCESTORID, A.DESCENDENTID, COUNT(A.DESCENDENTID)
FROM CONFANCESTORS A, CONTENT B
WHERE B.CONTENTID = A.DESCENDENTID
GROUP BY A.ANCESTORID, A.DESCENDENTID
HAVING COUNT(A.DESCENDENTID) > 1
ORDER BY 3 DESC