-- DETECT HOW MANY VALUES DO YOU HAVE IN Development panel
-- FYI: that info is like SQL cache
SELECT count(ID) FROM AO_575BF5_PROVIDER_ISSUE;

-- truncate AO_575BF5_DEV_SUMMARY;

-- DETECT AND CLEAN DEV SUMMARY INFO
SELECT count(ID) FROM AO_575BF5_DEV_SUMMARY;

-- truncate AO_575BF5_PROVIDER_ISSUE;