/*
 *
 * Get top 10 automation rules longer than 1 sec
 *
 */

SELECT "FINISH_TIME_MILLIS"-"START_TIME_MILLIS" as duration,  *
FROM "AO_9B2E3B_IF_COND_EXECUTION"
WHERE "FINISH_TIME_MILLIS"-"START_TIME_MILLIS" > 1000
ORDER BY 1 DESC
LIMIT 10;